[project]
name = "vhsh"
dynamic = ["version"]
requires-python = "==3.12"
dependencies = ["PyOpenGL", "glfw", "imgui[glfw]", "numpy"]

[project.optional-dependencies]
all = ["vhsh[midi,audio,watch,import]"]
watch = ["watchfiles"]
midi = ["mido[ports-rtmidi]"]
audio = ["PyAudio"]
import = ["requests"]

[project.scripts]
vhsh = "vhsh.__main__:main"

[dependency-groups]
dev = ["ruff", "pyright", "pyimgui-stubs"]
test = ["pytest"]

[tool.setuptools]
packages = ["vhsh"]
dynamic = { "version" = { attr = "vhsh.__version__" } }

[tool.pyright]
venvPath = "."
venv = ".venv"
