[project]
name = "vhsh"
dynamic = ["version"]
description = "VideoHomeShader: A demo tool for digitally assisted analog vjaying"
readme = "README.md"
authors = [
    { name = "Philipp Stephan", email = "mail@philippstephan.de" }
]
requires-python = "~=3.12.0"  # pyimgui
dependencies = ["PyOpenGL", "glfw", "imgui[glfw]", "numpy"]
# https://peps.python.org/pep-0771/
# default-optional-dependency-keys = ["watch", "import"]

[project.optional-dependencies]
all = ["vhsh[midi,audio,watch,import]"]
watch = ["watchfiles"]
midi = ["mido[ports-rtmidi]"]
audio = ["PyAudio"]
import = ["requests"]

[project.scripts]
vhsh = "vhsh.__main__:main"

[dependency-groups]
dev = [
    "ruff",
    "ty",
    "pyimgui-stubs",
    "mido>=1.3.4.dev0", # https://github.com/mido/mido/pull/624
]
test = ["pytest"]

# TODO uv build does not support scm verison
# https://github.com/astral-sh/uv/issues/14037
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["vhsh"]
package-dir = {"" = "src"}
dynamic = { "version" = { attr = "vhsh.__version__" } }

[tool.uv]
default-groups = ["dev", "test"]
environments = [
    "sys_platform == 'darwin'",
    "sys_platform == 'linux'",
]
[tool.uv.sources]
pyimgui-stubs = { git = "https://github.com/phistep/pyimgui-stubs", branch = "plot_histogram" }
mido = [
    # FIXME missing attributes, see https://github.com/mido/mido/issues/641
    # FIXME always pulled in, even without --dev
    # see https://github.com/astral-sh/uv/issues/17252
    { git = "https://github.com/mido/mido", group = "dev" },
]

[tool.ruff.lint]
select = ["E", "F", "I", "RUF100", "TC"]

[tool.ruff.lint.isort]
combine-as-imports = true


[tool.ty.src]
exclude = [
    # FIXME https://github.com/astral-sh/ty/issues/691
    # see https://docs.astral.sh/ty/reference/typing-faq/#does-ty-support-pep-723-inline-metadata-scripts
    "tests/plot_logscale.py",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
log_level = "DEBUG"
