[project]
name = "vhsh"
dynamic = ["version"]
description = "VideoHomeShader: A demo tool for digitally assisted analog vjaying"
readme = "README.md"
authors = [
    { name = "Philipp Stephan", email = "mail@philippstephan.de" }
]
requires-python = "~=3.12.0"  # pyimgui
dependencies = ["PyOpenGL", "glfw", "imgui[glfw]", "numpy"]
# https://peps.python.org/pep-0771/
# default-optional-dependency-keys = ["watch", "import"]

[project.optional-dependencies]
all = ["vhsh[midi,audio,watch,import]"]
watch = ["watchfiles"]
midi = ["mido[ports-rtmidi]"]
audio = ["PyAudio"]
import = ["requests"]

[project.scripts]
vhsh = "vhsh.__main__:main"

[dependency-groups]
dev = ["ruff", "ty", "pyimgui-stubs"]
test = ["pytest"]

# TODO uv build does not support scm verison
# https://github.com/astral-sh/uv/issues/14037
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["vhsh"]
package-dir = {"" = "src"}
dynamic = { "version" = { attr = "vhsh.__version__" } }

[tool.uv]
default-groups = ["dev", "test"]
environments = [
    "sys_platform == 'darwin'",
    "sys_platform == 'linux'",
]
[tool.uv.sources]
pyimgui-stubs = { git = "https://github.com/phistep/pyimgui-stubs", branch = "plot_histogram" }

[tool.ruff.lint]
select = ["E", "F", "I", "RUF100", "TC"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
log_level = "DEBUG"
