from typing import Protocol

from .gl_types import UniformValue


class Actions(Protocol):
    def prev_shader(self): ...
    def next_shader(self): ...
    def prev_preset(self, n: int = 1): ...
    def next_preset(self, n: int = 1): ...
    def write_file(self,
                   presets: bool = True,
                   uniforms: bool = False,
                   new_preset: str | None = None): ...
    # TODO @properties
    def set_time_running(self, value: bool): ...
    def set_show_gui(self, value: bool): ...
    def get_midi_mapping(self, cc: int) -> str: ...
    def set_uniform_value(self,
                          name: str,
                          value: UniformValue,
                          normalized: bool = False): ...
    # TODO -> fmt_error, also display in GUI
    def _print_error(self, e: Exception | str): ...
