[scene]
prev = 58
next = 59
# auto_play = 46
# record = 45

[preset]
prev = 61
next = 62
save = 60

[ui]
toggle = 45
# transparency =
# floating =
# fullscreen =

[parameter.time]
toggle = 41
# decrease_speed = 43
# increase_speed = 44

# [parameter.custom]
# slider = [1, 2, 3, 4]
# knob = [10, 11, 12, 13]
# button = [20, 21, 22, 23]
# master_button = 42
